/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as ComoInvestigamosRouteImport } from './routes/como-investigamos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestigacionSlugRouteImport } from './routes/investigacion.$slug'

const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoInvestigamosRoute = ComoInvestigamosRouteImport.update({
  id: '/como-investigamos',
  path: '/como-investigamos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionSlugRoute = InvestigacionSlugRouteImport.update({
  id: '/investigacion/$slug',
  path: '/investigacion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-investigamos': typeof ComoInvestigamosRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/investigacion/$slug': typeof InvestigacionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-investigamos': typeof ComoInvestigamosRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/investigacion/$slug': typeof InvestigacionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-investigamos': typeof ComoInvestigamosRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/investigacion/$slug': typeof InvestigacionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-investigamos'
    | '/quienes-somos'
    | '/investigacion/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/como-investigamos' | '/quienes-somos' | '/investigacion/$slug'
  id:
    | '__root__'
    | '/'
    | '/como-investigamos'
    | '/quienes-somos'
    | '/investigacion/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoInvestigamosRoute: typeof ComoInvestigamosRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  InvestigacionSlugRoute: typeof InvestigacionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-investigamos': {
      id: '/como-investigamos'
      path: '/como-investigamos'
      fullPath: '/como-investigamos'
      preLoaderRoute: typeof ComoInvestigamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigacion/$slug': {
      id: '/investigacion/$slug'
      path: '/investigacion/$slug'
      fullPath: '/investigacion/$slug'
      preLoaderRoute: typeof InvestigacionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoInvestigamosRoute: ComoInvestigamosRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  InvestigacionSlugRoute: InvestigacionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
